server:
  port: 8085
spring:
  r2dbc:
    username: test
    password: test
    url: r2dbc:postgresql://postgres:5432/testdb
    pool:
      enabled: true
      initial-size: 10
      max-idle-time: 1m
      max-size: 30
  sql:
    init:
      platform: postgresql
      mode: always
  data:
    r2dbc:
      repositories:
        enabled: true
jwt:
  secret: 9be5fa455defebc4c61d0d9c84cf87928741050cb1e6ff9278912648e9d5419d
  expiration: 3600
logging:
  level:
    root: INFO
    org:
      springframework:
        r2dbc: DEBUG
  file:
    name: ./logs/item-service.log
    org:
      springframework:
        r2dbc: DEBUG
kafka-group-id:
  auction: auction-consumer-group
cloud:
  aws:
    region:
      static: eu-north-1
    s3:
      endpoint: http://localstack:4566
    credentials:
      access-key: test
      secret-key: test

s3:
  bucket:
    name: auction-item
