server:
  port: 8082

spring:
  r2dbc:
    username: test
    password: test
    url: r2dbc:postgresql://postgres:5432/testdb
    pool:
      enabled: true
      initial-size: 10
      max-idle-time: 1m
      max-size: 30
  sql:
    init:
      platform: postgresql
      mode: always
  data:
    r2dbc:
      repositories:
        enabled: true

logging:
  level:
    root: INFO
    org:
      springframework:
        r2dbc: DEBUG
  file:
    name: /user-service.log
jwt:
  secret: 9be5fa455defebc4c61d0d9c84cf87928741050cb1e6ff9278912648e9d5419d
  expiration: 3600

topic:
  user: find-user-events

config:
  properties-insync-rep: min.insync.replicas
  replicas-num: 1
