spring:
  redis:
    host: redis
    port: 6379
  jackson:
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
      accept-single-value-as-array: true
    default-property-inclusion: non_null
    mapper:
      accept-case-insensitive-properties: true
