server:
  port: 8084
spring:
  r2dbc:
    username: postgres
    password: 1234
    url: r2dbc:postgresql://localhost:5432/test
    pool:
      enabled: true
      initial-size: 10
      max-idle-time: 1m
      max-size: 30
  sql:
    init:
      platform: postgresql
      mode: always
  data:
    r2dbc:
      repositories:
        enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
logging:
  level:
    root: INFO
  file:
    name: /Users/mryhnwbyzqy/Desktop/Auction/AuctionService/auction-service.log








