server:
  port: 8086
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    mongodb:
      host: localhost
      port: 27017
      database: auction

logging:
  level:
    root: INFO
  file:
    name: /Users/mryhnwbyzqy/Desktop/Auction/AuctionService/notification-service.log
    org:
      springframework:
        r2dbc: DEBUG



