name: Build
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build services
        run: |
          cd core && mvn clean install -DskipTests && cd ..
          for d in GatewayService AuctionService UserService BidService InvitationService ItemService NotificationService SecurityService; do
            cd $d && mvn clean package -DskipTests && cd ..
          done

      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: |
            **/target/*.jar
