name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml

  service-tests:
    uses: ./.github/workflows/service-tests.yml

  api-tests:
    uses: ./.github/workflows/api-tests.yml
